### ISSUE TITLE
undefined joiOptions should not throw TypeError

### ISSUE THREAD

**Issue by schettino** [feathers-plus/feathers-hooks-validate-joi#8]
Currently, not setting at least an empty object, the hook will throw a TypeError.

I have wrote a test about it. Here it is where I define it as undefined.
https://github.com/schettino/feathers-hooks-validate-joi/blob/59dfcdf205992583cf5365a59ed844f33002f413/test/invalid_spec.js#L70

![image](https://user-images.githubusercontent.com/7825467/38142743-ed876814-3413-11e8-978a-c74623a4f639.png)

**Comment by marshallswain** [comment]
Closing this now that #9 is merged.
